/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Consultas;

import Formularios.Conexion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maria
 */
public class Consultaempleados extends javax.swing.JFrame {

    /**
     * Creates new form Consultaempleados
     */
    public Consultaempleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnmostrar = new javax.swing.JButton();
        txtbuscarempleados = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Toque el botón mostrar para ver todos los empleados.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 18))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnmostrar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btnmostrar.setText("Mostrar");
        btnmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarActionPerformed(evt);
            }
        });

        txtbuscarempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarempleadosActionPerformed(evt);
            }
        });

        btnbuscar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa.png"))); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnmostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtbuscarempleados, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbuscar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnmostrar)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbuscarempleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbuscar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 823, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarActionPerformed
  Conexion mysql = new Conexion();
        java.sql.Connection cn = mysql.Conectar();

        String query = "SELECT * FROM empleados";
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("EmpleadoID");
        model.addColumn("Nombre Completo");
        model.addColumn("Edad");
        model.addColumn("Fecha Nacimiento");
        model.addColumn("Teléfono");
        model.addColumn("Cédula");
        model.addColumn("Horario de Trabajo");
        model.addColumn("Cargo");
        model.addColumn("Tipo de Seguro");
        model.addColumn("Tipo de Sueldo");
        model.addColumn("Sueldo");
        model.addColumn("Fecha Ingreso");
        model.addColumn("Estado");

        try (PreparedStatement ps = cn.prepareStatement(query); ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("EmpleadoID"),
                    rs.getString("nombrecompleto"),
                    rs.getString("edad"),
                    rs.getString("fechanacimiento"),
                    rs.getString("telefono"),
                    rs.getString("cedula"),
                    rs.getString("horariotrabajo"),
                    rs.getString("cargo"),
                    rs.getString("tiposeguro"),
                    rs.getString("tiposueldo"),
                    rs.getString("sueldo"),
                    rs.getString("fechaingreso"),
                    rs.getString("estado")
                });
            }
            jTable1.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al mostrar los empleados: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }                                          

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {                                              
        Conexion mysql = new Conexion();
        java.sql.Connection cn = mysql.Conectar();
        
        ResultSet rs;
        PreparedStatement ps;
   
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            jTable1.setModel(modelo);
            
            ps=cn.prepareStatement("SELECT * FROM EMPLEADOS");
            rs=ps.executeQuery();
                        
            java.sql.ResultSetMetaData rsMd =rs.getMetaData();
            int cColumnas = rsMd.getColumnCount();
            modelo.addColumn("EmpleadoID");
            modelo.addColumn("Nombrecompleto");
            modelo.addColumn("Edad");
            modelo.addColumn("Fechanacimiento");
            modelo.addColumn("telefono");
            modelo.addColumn("cedula");
            modelo.addColumn("horariotrabajo");
            modelo.addColumn("cargo");
            modelo.addColumn("tiposeguro");
            modelo.addColumn("tiposueldo");
            modelo.addColumn("sueldo");
            modelo.addColumn("fechaingreso");
            modelo.addColumn("estado");
            
            while (rs.next()){
                Object[] filas = new Object [cColumnas];
                for (int i=0; i<cColumnas;i++){
                    filas[i]=rs.getObject(i+1);
                }
                modelo.addRow(filas);
                    
            }
    
         }catch(SQLException e){
  
                JOptionPane.showMessageDialog(null, "No se pudieron mostrar los datos  " + e.getMessage());
   }
    }//GEN-LAST:event_btnmostrarActionPerformed

    private void txtbuscarempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarempleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarempleadosActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        Conexion mysql = new Conexion();
        java.sql.Connection cn = mysql.Conectar();

        DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("EmpleadoID");
            modelo.addColumn("Nombrecompleto");
            modelo.addColumn("Edad");
            modelo.addColumn("Fechanacimiento");
            modelo.addColumn("telefono");
            modelo.addColumn("cedula");
            modelo.addColumn("horariotrabajo");
            modelo.addColumn("cargo");
            modelo.addColumn("tiposeguro");
            modelo.addColumn("tiposueldo");
            modelo.addColumn("sueldo");
            modelo.addColumn("fechaingreso");
            modelo.addColumn("estado");

        String filtro = txtbuscarempleados.getText().trim();

        try {
            String query = "SELECT * FROM empleados where EmpleadoID like ? or Nombrecompleto like ? ";
            PreparedStatement ps = cn.prepareStatement(query);
            ps.setString(1, "%" + filtro + "%");
            ps.setString(2, "%" + filtro + "%");

            ResultSet rs = ps.executeQuery();

            modelo.setRowCount(0);

            while (rs.next()) {
                Object[] fila = new Object[13];

                fila[0] = rs.getInt("EmpleadoID");
                fila[1] = rs.getString("Nombrecompleto");
                fila[2] = rs.getString("edad");
                fila[3] = rs.getString("fechanacimiento");
                fila[4] = rs.getString("telefono");
                fila[5] = rs.getString("cedula");
                fila[6] = rs.getString("horariotrabajo");
                fila[7] = rs.getString("cargo");
                fila[8] = rs.getString("tiposeguro");
                fila[9] = rs.getString("tiposueldo");
                fila[10] = rs.getString("sueldo");
                fila[11] = rs.getString("fechaingreso");
                fila[12] = rs.getString("estado");
                

                modelo.addRow(fila);
            }

            jTable1.setModel(modelo);

            ps.close();
            rs.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al obtener los registros: " + e.getMessage());
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultaempleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultaempleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultaempleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultaempleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultaempleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnmostrar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtbuscarempleados;
    // End of variables declaration//GEN-END:variables
}
