/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import java.sql.Connection;
import java.sql.DriverManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.view.JasperViewer;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class Cotizacion extends javax.swing.JFrame {

    /**
     * Creates new form Cotizacion
     */
    public Cotizacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelfondo = new javax.swing.JPanel();
        iconol = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Cotizaciones = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        fecha_cotizacion = new javax.swing.JTextField();
        nombree = new javax.swing.JLabel();
        nombrer = new javax.swing.JLabel();
        serial = new javax.swing.JLabel();
        Listaynumeros = new javax.swing.JLabel();
        placa = new javax.swing.JLabel();
        fechadeentrega = new javax.swing.JLabel();
        Lugarynombre = new javax.swing.JLabel();
        nombre_emisor = new javax.swing.JTextField();
        nombre_receptor = new javax.swing.JTextField();
        numero_serial_paquete = new javax.swing.JTextField();
        lista_objetos = new javax.swing.JTextField();
        placa_vehiculo = new javax.swing.JTextField();
        fecha_entrega = new javax.swing.JTextField();
        lugar_nombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnatras = new javax.swing.JButton();
        button1 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelfondo.setBackground(new java.awt.Color(55, 195, 239));

        iconol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/solicitud-de-cotizacion.png"))); // NOI18N

        javax.swing.GroupLayout panelfondoLayout = new javax.swing.GroupLayout(panelfondo);
        panelfondo.setLayout(panelfondoLayout);
        panelfondoLayout.setHorizontalGroup(
            panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfondoLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(iconol)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelfondoLayout.setVerticalGroup(
            panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfondoLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(iconol)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        Cotizaciones.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        Cotizaciones.setText("Formulario de cotización");

        fecha.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        fecha.setText("Fecha de cotizacion:");

        fecha_cotizacion.setText("aaaa-mm-dd");
        fecha_cotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha_cotizacionActionPerformed(evt);
            }
        });

        nombree.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        nombree.setText("Nombre de emisor:");

        nombrer.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        nombrer.setText("Nombre de receptor:");

        serial.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        serial.setText("Numero de serial del paquete:");

        Listaynumeros.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        Listaynumeros.setText("Lista y numero de objetos:");

        placa.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        placa.setText("Placa de vehiculo involucrado:");

        fechadeentrega.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        fechadeentrega.setText("Fecha de entrega:");

        Lugarynombre.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        Lugarynombre.setText("Lugar y nombre del domicilio:");

        nombre_emisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_emisorActionPerformed(evt);
            }
        });

        placa_vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placa_vehiculoActionPerformed(evt);
            }
        });

        fecha_entrega.setText("aaaa-mm-dd");
        fecha_entrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha_entregaActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(55, 195, 239));
        jButton1.setText("Enviar cotización.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnatras.setBackground(new java.awt.Color(55, 195, 239));
        btnatras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/previous.png"))); // NOI18N
        btnatras.setText("Volver");
        btnatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasActionPerformed(evt);
            }
        });

        button1.setActionCommand("Imprimir");
        button1.setLabel("Imprimir\n");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombree)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombre_emisor, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(serial)
                                        .addGap(18, 18, 18)
                                        .addComponent(numero_serial_paquete, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nombrer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nombre_receptor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(placa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(placa_vehiculo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fechadeentrega)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fecha_entrega)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Lugarynombre)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lugar_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(15, 15, 15))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(btnatras, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addComponent(jButton1)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Listaynumeros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lista_objetos, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(105, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cotizaciones)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fecha_cotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelfondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Cotizaciones)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fecha)
                            .addComponent(fecha_cotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombree)
                    .addComponent(nombre_emisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrer)
                    .addComponent(nombre_receptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serial)
                    .addComponent(numero_serial_paquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Listaynumeros)
                    .addComponent(lista_objetos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placa)
                    .addComponent(placa_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechadeentrega)
                    .addComponent(fecha_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lugarynombre)
                    .addComponent(lugar_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnatras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(85, 85, 85))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecha_cotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha_cotizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha_cotizacionActionPerformed

    private void nombre_emisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_emisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_emisorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Conexion mysql = new Conexion();
    java.sql.Connection cn = mysql.Conectar();
    
    int id_cotizacion = 0;
    String fecha_cot = fecha_cotizacion.getText();
    String nombre_e = nombre_emisor.getText();
    String nombre_r = nombre_receptor.getText();
    String serial = numero_serial_paquete.getText();
    String lista = lista_objetos.getText();
    String placa = placa_vehiculo.getText();
    String fecha_ent = fecha_entrega.getText();
    String lugar = lugar_nombre.getText();
    
    
    
    String cotizacion = "INSERT INTO cotizaciones(CotizacionID, FechaCotizacion, NombreEmisor, NombreReceptor, NumeroSerialPaquete, ListaYNumeroObjetos, PlacaVehiculoInvolucrado, FechaEntrega, LugarDeDomicilio_NombreDomicilio) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)";
    try (PreparedStatement ps = cn.prepareStatement(cotizacion)){
            ps.setInt(1, id_cotizacion);
            ps.setString(2, fecha_cot);
            ps.setString(3, nombre_e);
            ps.setString(4, nombre_r);
            ps.setString(5, serial);
            ps.setString(6, lista);
            ps.setString(7, placa);
            ps.setString(8, fecha_ent);
            ps.setString(9, lugar);
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos guardados correctamente.");
        
        }
        catch (SQLException e){
                JOptionPane.showMessageDialog(null, "No se pudo guardar: " + e.getMessage());
                
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasActionPerformed
         this.setVisible(false);
        Opciones opcion = new Opciones();
        opcion.setVisible(true);
    
    }//GEN-LAST:event_btnatrasActionPerformed

    private void fecha_entregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha_entregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha_entregaActionPerformed

    private void placa_vehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placa_vehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placa_vehiculoActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
     Conexion mysql = new Conexion();

      
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try (java.sql.Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/destiny" , "root", "Marianny19")) {
                String reportPath = "C:\\Users\\maria\\JaspersoftWorkspace\\MyReports\\Cotizacion.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(reportPath);
                JasperPrint jp = JasperFillManager.fillReport(jr, null, cn);
                JasperViewer.viewReport(jp);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cotizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cotizaciones;
    private javax.swing.JLabel Listaynumeros;
    private javax.swing.JLabel Lugarynombre;
    private javax.swing.JButton btnatras;
    private java.awt.Button button1;
    private javax.swing.JLabel fecha;
    private javax.swing.JTextField fecha_cotizacion;
    private javax.swing.JTextField fecha_entrega;
    private javax.swing.JLabel fechadeentrega;
    private javax.swing.JLabel iconol;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lista_objetos;
    private javax.swing.JTextField lugar_nombre;
    private javax.swing.JTextField nombre_emisor;
    private javax.swing.JTextField nombre_receptor;
    private javax.swing.JLabel nombree;
    private javax.swing.JLabel nombrer;
    private javax.swing.JTextField numero_serial_paquete;
    private javax.swing.JPanel panelfondo;
    private javax.swing.JLabel placa;
    private javax.swing.JTextField placa_vehiculo;
    private javax.swing.JLabel serial;
    // End of variables declaration//GEN-END:variables
}
