package Formularios;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import Consultas.Consultacliente;
import Consultas.Consultacotizacion;
import Consultas.Consultaempleados;
import Consultas.Consultaequipos;
import Consultas.Consultapago;
import Consultas.Consultapaquetesenelinventario;
import Consultas.Consultausuarios;
import Consultas.consultaconductores;
import Consultas.consultafactura;
import Consultas.consultapaquetes;
import Consultas.consultasucursales;
import Consultas.consultatransporte;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maria
 */
public class Receptor extends javax.swing.JFrame {

    /**
     * Creates new form Receptor
     */
   
    public Receptor() {
        initComponents();
        Conexion mysql = new Conexion();
        java.sql.Connection cn = mysql.Conectar();
           
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelingresar = new javax.swing.JPanel();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtidreceptor = new javax.swing.JTextField();
        txtdomicilio = new javax.swing.JTextField();
        txtnumerocasa = new javax.swing.JTextField();
        txtcodigopostal = new javax.swing.JTextField();
        btnregistrar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btnmostrar = new javax.swing.JButton();
        txttelefono = new javax.swing.JTextField();
        btneliminar = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        txtestado = new javax.swing.JTextField();
        txtprovincia = new javax.swing.JTextField();
        txtcedulacliente = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnusuario = new javax.swing.JMenu();
        mnitemusuario = new javax.swing.JMenuItem();
        mnpaquete = new javax.swing.JMenu();
        mnitempaquete = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnitemreceptor = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnitemcliente = new javax.swing.JMenuItem();
        mntransporte = new javax.swing.JMenu();
        mnitemtransporte = new javax.swing.JMenuItem();
        mnequipo = new javax.swing.JMenu();
        mnitemequipo = new javax.swing.JMenuItem();
        mnsucursal = new javax.swing.JMenu();
        mnitemsucursal = new javax.swing.JMenuItem();
        mnconductor = new javax.swing.JMenu();
        mniemconductor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem7 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem8 = new javax.swing.JCheckBoxMenuItem();
        consultatransporte = new javax.swing.JCheckBoxMenuItem();
        consultaconductores = new javax.swing.JCheckBoxMenuItem();
        Consultaempleados = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem11 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem12 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem10 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        mnsalir = new javax.swing.JMenu();
        mnitemsalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelingresar.setBackground(new java.awt.Color(153, 204, 255));
        panelingresar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese la información del receptor.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 18))); // NOI18N

        txtnombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 12))); // NOI18N
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        txtapellido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 12))); // NOI18N
        txtapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidoActionPerformed(evt);
            }
        });

        txtidreceptor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Id receptor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 12))); // NOI18N
        txtidreceptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidreceptorActionPerformed(evt);
            }
        });

        txtdomicilio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Domicilio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 12))); // NOI18N
        txtdomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdomicilioActionPerformed(evt);
            }
        });

        txtnumerocasa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Número de casa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 12))); // NOI18N
        txtnumerocasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumerocasaActionPerformed(evt);
            }
        });

        txtcodigopostal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Código postal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 12))); // NOI18N
        txtcodigopostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigopostalActionPerformed(evt);
            }
        });

        btnregistrar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });

        btnactualizar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btnmostrar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        btnmostrar.setText("Mostrar");
        btnmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarActionPerformed(evt);
            }
        });

        txttelefono.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Teléfono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 12))); // NOI18N
        txttelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonoActionPerformed(evt);
            }
        });

        btneliminar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnvolver.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        btnvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/previous.png"))); // NOI18N
        btnvolver.setText("Volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        btnbuscar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa.png"))); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        txtestado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 12))); // NOI18N
        txtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestadoActionPerformed(evt);
            }
        });

        txtprovincia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Provincia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 12))); // NOI18N
        txtprovincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprovinciaActionPerformed(evt);
            }
        });

        txtcedulacliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cédula Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 12))); // NOI18N
        txtcedulacliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedulaclienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelingresarLayout = new javax.swing.GroupLayout(panelingresar);
        panelingresar.setLayout(panelingresarLayout);
        panelingresarLayout.setHorizontalGroup(
            panelingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelingresarLayout.createSequentialGroup()
                .addGroup(panelingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelingresarLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(panelingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelingresarLayout.createSequentialGroup()
                                .addComponent(txtidreceptor, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnbuscar))
                            .addComponent(txtdomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnumerocasa, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcodigopostal, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprovincia, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcedulacliente, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelingresarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnvolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnregistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnactualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnmostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneliminar)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelingresarLayout.setVerticalGroup(
            panelingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelingresarLayout.createSequentialGroup()
                .addGroup(panelingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidreceptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelingresarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnbuscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnumerocasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcodigopostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtprovincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcedulacliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnvolver)
                    .addComponent(btnregistrar)
                    .addComponent(btnactualizar)
                    .addComponent(btnmostrar)
                    .addComponent(btneliminar))
                .addGap(69, 69, 69))
        );

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informaciones de los receptores.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 18))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        jLabel2.setText("Toque el botón mostrar para ver todos los datos de los receptores.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        jLabel1.setText("Información de receptor.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        mnusuario.setBackground(new java.awt.Color(255, 204, 204));
        mnusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userLabel.png"))); // NOI18N
        mnusuario.setText("Usuario");
        mnusuario.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemusuario.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userLabel.png"))); // NOI18N
        mnitemusuario.setText("Registro de usuario");
        mnitemusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemusuarioActionPerformed(evt);
            }
        });
        mnusuario.add(mnitemusuario);

        jMenuBar1.add(mnusuario);

        mnpaquete.setBackground(new java.awt.Color(153, 204, 255));
        mnpaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/box.png"))); // NOI18N
        mnpaquete.setText("Paquete");
        mnpaquete.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitempaquete.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitempaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/box.png"))); // NOI18N
        mnitempaquete.setText("Registro de paquete");
        mnitempaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitempaqueteActionPerformed(evt);
            }
        });
        mnpaquete.add(mnitempaquete);

        jMenuBar1.add(mnpaquete);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/receiver.png"))); // NOI18N
        jMenu3.setText("Receptor");
        jMenu3.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemreceptor.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemreceptor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/receiver.png"))); // NOI18N
        mnitemreceptor.setText("Registrar receptor");
        mnitemreceptor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemreceptorActionPerformed(evt);
            }
        });
        jMenu3.add(mnitemreceptor);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-avatar.png"))); // NOI18N
        jMenu4.setText("Cliente");
        jMenu4.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemcliente.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-avatar.png"))); // NOI18N
        mnitemcliente.setText("Registrar cliente");
        mnitemcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemclienteActionPerformed(evt);
            }
        });
        jMenu4.add(mnitemcliente);

        jMenuBar1.add(jMenu4);

        mntransporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/truck.png"))); // NOI18N
        mntransporte.setText("Transporte");
        mntransporte.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemtransporte.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemtransporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/truck.png"))); // NOI18N
        mnitemtransporte.setText("Registrar un nuevo transporte");
        mnitemtransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemtransporteActionPerformed(evt);
            }
        });
        mntransporte.add(mnitemtransporte);

        jMenuBar1.add(mntransporte);

        mnequipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/computer.png"))); // NOI18N
        mnequipo.setText("Equipo");
        mnequipo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemequipo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemequipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/computer.png"))); // NOI18N
        mnitemequipo.setText("Registrar un nuevo equipo al inventario");
        mnitemequipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemequipoActionPerformed(evt);
            }
        });
        mnequipo.add(mnitemequipo);

        jMenuBar1.add(mnequipo);

        mnsucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/office.png"))); // NOI18N
        mnsucursal.setText("Sucursal");
        mnsucursal.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemsucursal.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemsucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/office.png"))); // NOI18N
        mnitemsucursal.setText("Registrar nueva sucursal.");
        mnitemsucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemsucursalActionPerformed(evt);
            }
        });
        mnsucursal.add(mnitemsucursal);

        jMenuBar1.add(mnsucursal);

        mnconductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/driver.png"))); // NOI18N
        mnconductor.setText("Conductores");
        mnconductor.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mniemconductor.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mniemconductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/driver.png"))); // NOI18N
        mniemconductor.setText("Registrar un nuevo conductor.");
        mniemconductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniemconductorActionPerformed(evt);
            }
        });
        mnconductor.add(mniemconductor);

        jMenuBar1.add(mnconductor);

        jMenu2.setText("Pago");
        jMenu2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        jRadioButtonMenuItem2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Registro de pago.");
        jMenu2.add(jRadioButtonMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/operator.png"))); // NOI18N
        jMenu1.setText("consultaequipo");
        jMenu1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Consultausuario");
        jCheckBoxMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userLabel.png"))); // NOI18N
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("Consultacliente");
        jCheckBoxMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-avatar.png"))); // NOI18N
        jCheckBoxMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem3);

        jCheckBoxMenuItem5.setSelected(true);
        jCheckBoxMenuItem5.setText("Consultafactura");
        jCheckBoxMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem5);

        jCheckBoxMenuItem7.setSelected(true);
        jCheckBoxMenuItem7.setText("Consultacotizacion");
        jCheckBoxMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem7);

        jCheckBoxMenuItem8.setSelected(true);
        jCheckBoxMenuItem8.setText("Consultaequipo");
        jCheckBoxMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem8);

        consultatransporte.setSelected(true);
        consultatransporte.setText("consultapaquete");
        consultatransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultatransporteActionPerformed(evt);
            }
        });
        jMenu1.add(consultatransporte);

        consultaconductores.setSelected(true);
        consultaconductores.setText("Consultatransporte");
        consultaconductores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaconductoresActionPerformed(evt);
            }
        });
        jMenu1.add(consultaconductores);

        Consultaempleados.setSelected(true);
        Consultaempleados.setText("Consultapago");
        Consultaempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaempleadosActionPerformed(evt);
            }
        });
        jMenu1.add(Consultaempleados);

        jCheckBoxMenuItem11.setSelected(true);
        jCheckBoxMenuItem11.setText("consultapaquetesenelinventario");
        jCheckBoxMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem11);

        jCheckBoxMenuItem12.setSelected(true);
        jCheckBoxMenuItem12.setText("consultaempleados");
        jCheckBoxMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem12);

        jCheckBoxMenuItem10.setSelected(true);
        jCheckBoxMenuItem10.setText("consultasucursal");
        jCheckBoxMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem10);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("consultaconductores");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem1);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Consulta receptores.");
        jMenu1.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu1);

        mnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        mnsalir.setText("Salir");
        mnsalir.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemsalir.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        mnitemsalir.setText("Salir.");
        mnitemsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemsalirActionPerformed(evt);
            }
        });
        mnsalir.add(mnitemsalir);

        jMenuBar1.add(mnsalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelingresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelingresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoActionPerformed

    private void txtidreceptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidreceptorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidreceptorActionPerformed

    private void txtdomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdomicilioActionPerformed

    private void txtnumerocasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumerocasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumerocasaActionPerformed

    private void txtcodigopostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigopostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigopostalActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        Conexion mysql = new Conexion();
        java.sql.Connection cn = mysql.Conectar();
         
        String ReceptorID = txtidreceptor.getText();
        String Nombre = txtnombre.getText();
        String Apellido = txtapellido.getText();
        String Telefono = txttelefono.getText();
        String Domicilio = txtdomicilio.getText();
        String Numerodecasa = txtnumerocasa.getText();
        String Codigopostal = txtcodigopostal.getText();
        String Estado = txtestado.getText();
        String provincia = txtprovincia.getText();
        
        String query="Update RECEPTORES set  ReceptorId=?, Nombre=?, Apellido=?, Telefono=?, Domicilio=?, Numerodecasa=?, Codigopostal=?, Estado=?, provincia=? where ReceptorId=? ";
try(PreparedStatement ps=cn.prepareStatement(query))  {
  
            ps.setString(1, ReceptorID);
            ps.setString(2, Nombre);
            ps.setString(3, Apellido);
            ps.setString(4, Telefono);
            ps.setString(5, Domicilio);
            ps.setString(6, Numerodecasa);
            ps.setString(7, Codigopostal);
            ps.setString(8, Estado);
            ps.setString(9, provincia);
            ps.setString(10, ReceptorID);
  
    
     ps.executeUpdate();
     JOptionPane.showMessageDialog(null, "datos actualizados correctamente");
     
}
catch(SQLException e){
    JOptionPane.showMessageDialog(null, "no se pudo actualizar correctamente"+e.getMessage());
}      
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
            Conexion mysql = new Conexion();
        java.sql.Connection cn = mysql.Conectar();
         
        String ReceptorID = txtidreceptor.getText();
        String Nombre = txtnombre.getText();
        String Apellido = txtapellido.getText();
        String Telefono = txttelefono.getText();
        String Domicilio = txtdomicilio.getText();
        String Numerodecasa = txtnumerocasa.getText();
        String Codigopostal = txtcodigopostal.getText();
        String Estado = txtestado.getText();
        String provincia = txtprovincia.getText();
        String cedulacliente = txtcedulacliente.getText();
        
         String receptores = "INSERT INTO receptores(ReceptorID, Nombre, Apellido, Telefono, Domicilio, NumeroDeCasa, CodigoPostal, provincia, ClienteID, estado) values(?, ?, ?, ?, ?, ?, ?,?,?,?)";
        try (PreparedStatement ps = cn.prepareStatement(receptores)){
           ps.setString(1, ReceptorID);
            ps.setString(2, Nombre);
            ps.setString(3, Apellido);
            ps.setString(4, Telefono);
            ps.setString(5, Domicilio);
            ps.setString(6, Numerodecasa);
            ps.setString(7, Codigopostal);
            ps.setString(8, provincia);
            ps.setString(9, cedulacliente);
            ps.setString(10,Estado);
           
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos guardados correctamente.");
        
        }
        catch (SQLException e){
                JOptionPane.showMessageDialog(null, "No se pudo guardar: " + e.getMessage());
                
                }
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarActionPerformed
     Conexion mysql = new Conexion();
     java.sql.Connection cn = mysql.Conectar();
        ResultSet rs;
     PreparedStatement ps;
   
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            jTable1.setModel(modelo);
            
            ps=cn.prepareStatement("SELECT * FROM RECEPTORES");
            rs=ps.executeQuery();
                        
            java.sql.ResultSetMetaData rsMd =rs.getMetaData();
            int cColumnas = rsMd.getColumnCount();
            modelo.addColumn("ReceptorID");
            modelo.addColumn("Nombre");
            modelo.addColumn("Apellido");
            modelo.addColumn("Telefono");
            modelo.addColumn("Domicilio");
            modelo.addColumn("Numerodecasa");
            modelo.addColumn("Codigopostal");
            modelo.addColumn("provincia");
            modelo.addColumn("Cédula Cliente");
                        modelo.addColumn("Estado");

            
            while (rs.next()){
                Object[] filas = new Object [cColumnas];
                for (int i=0; i<cColumnas;i++){
                    filas[i]=rs.getObject(i+1);
                }
                modelo.addRow(filas);
                    
            }
    
         }catch(SQLException e){
  
                JOptionPane.showMessageDialog(null, "No se pudieron mostrar los datos  " + e.getMessage());
   }
    }//GEN-LAST:event_btnmostrarActionPerformed

    private void txttelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        this.setVisible(false);
        Opciones opcion = new Opciones();
        opcion.setVisible(true);
    }//GEN-LAST:event_btnvolverActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        Conexion mysql = new Conexion();
        java.sql.Connection cn = mysql.Conectar();
        ResultSet rs;
        PreparedStatement ps;

    try {
        String ReceptorId = (txtidreceptor.getText());
        String query = "select * from receptores where ReceptorID = ?";
        ps = cn.prepareStatement(query);
        ps.setString(1, ReceptorId);
        rs = ps.executeQuery();

        if (rs.next()) {
            txtidreceptor.setText(rs.getString("ReceptorID"));
            txtnombre.setText(rs.getString("Nombre"));
            txtapellido.setText(rs.getString("Apellido"));
            txttelefono.setText(rs.getString("Telefono"));
            txtdomicilio.setText(rs.getString("Domicilio"));
            txtnumerocasa.setText(rs.getString("NumerodeCasa"));
            txtcodigopostal.setText(rs.getString("codigopostal"));
            txtestado.setText(rs.getString("Estado"));
            txtprovincia.setText(rs.getString("Provincia"));
        } else {
            JOptionPane.showMessageDialog(null, "Receptor no encontrado.");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al buscar los datos: " + e.getMessage());
    }
        
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
      Conexion mysql = new Conexion();
    java.sql.Connection cn = mysql.Conectar();

    try {
        String ReceptorID = txtidreceptor.getText();
        
        String query = "update receptores set Estado = 'Inactivo' where ReceptorID = ?";
        try (PreparedStatement ps = cn.prepareStatement(query)) {
            ps.setString(1, ReceptorID);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Estado del receptor actualizado a 'Inactivo' correctamente.");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "El ID del receptor debe ser un número válido.");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "No se pudo actualizar el estado: " + e.getMessage());
    }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void txtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoActionPerformed

    private void mnitemusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemusuarioActionPerformed
        this.setVisible(false);
        FormRegistro Usuario = new FormRegistro();
        Usuario.setVisible(true);
    }//GEN-LAST:event_mnitemusuarioActionPerformed

    private void mnitempaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitempaqueteActionPerformed
        this.setVisible(false);
        Tablapaquete paquete = new Tablapaquete();
        paquete.setVisible(true);
    }//GEN-LAST:event_mnitempaqueteActionPerformed

    private void mnitemreceptorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemreceptorActionPerformed
        this.setVisible(false);
        Receptor receptor1 = new Receptor();
        receptor1.setVisible(true);
    }//GEN-LAST:event_mnitemreceptorActionPerformed

    private void mnitemclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemclienteActionPerformed
        this.setVisible(false);
        Registrocliente cliente1 = new Registrocliente();
        cliente1.setVisible(true);
    }//GEN-LAST:event_mnitemclienteActionPerformed

    private void mnitemtransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemtransporteActionPerformed
        this.setVisible(false);
        Transporte transporte1= new Transporte();
        transporte1.setVisible(true);
    }//GEN-LAST:event_mnitemtransporteActionPerformed

    private void mnitemequipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemequipoActionPerformed
        this.setVisible(false);
        Registro_equipo equipo1 = new Registro_equipo();
        equipo1.setVisible(true);
    }//GEN-LAST:event_mnitemequipoActionPerformed

    private void mnitemsucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemsucursalActionPerformed
        this.setVisible(false);
        Sucursales sucursal1 = new Sucursales();
        sucursal1.setVisible(true);
    }//GEN-LAST:event_mnitemsucursalActionPerformed

    private void mniemconductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniemconductorActionPerformed
        this.setVisible(false);
        Registro_conductores conductor1 = new Registro_conductores();
        conductor1.setVisible(true);
    }//GEN-LAST:event_mniemconductorActionPerformed

    private void mnitemsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemsalirActionPerformed
        this.setVisible(false);
        FormLogin Login1 = new FormLogin();
        Login1.setVisible(true);
    }//GEN-LAST:event_mnitemsalirActionPerformed

    private void txtprovinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprovinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprovinciaActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
      this.setVisible(false);
        Consultausuarios usuarios1 = new Consultausuarios();
        usuarios1.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jCheckBoxMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem3ActionPerformed
      this.setVisible(false);
        Consultacliente cliente = new Consultacliente();
        cliente.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem3ActionPerformed

    private void jCheckBoxMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem5ActionPerformed
     this.setVisible(false);
     consultafactura factura = new consultafactura();
     factura.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem5ActionPerformed

    private void jCheckBoxMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem7ActionPerformed
    this.setVisible(false);
        Consultacotizacion cotizacion = new Consultacotizacion();
        cotizacion.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem7ActionPerformed

    private void jCheckBoxMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem8ActionPerformed
     this.setVisible(false);
        consultapaquetes paquete = new consultapaquetes();
        paquete.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem8ActionPerformed

    private void consultatransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultatransporteActionPerformed
     this.setVisible(false);
        Consultausuarios usuarios1 = new Consultausuarios();
        usuarios1.setVisible(true);
    }//GEN-LAST:event_consultatransporteActionPerformed

    private void consultaconductoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaconductoresActionPerformed
    this.setVisible(false);
        consultatransporte transporte = new consultatransporte();
        transporte.setVisible(true);
    }//GEN-LAST:event_consultaconductoresActionPerformed

    private void ConsultaempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaempleadosActionPerformed
    this.setVisible(false);
       Consultapago pago = new Consultapago();
        pago.setVisible(true);
    }//GEN-LAST:event_ConsultaempleadosActionPerformed

    private void jCheckBoxMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem11ActionPerformed
     this.setVisible(false);
        Consultapaquetesenelinventario paquete = new Consultapaquetesenelinventario();
        paquete.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem11ActionPerformed

    private void jCheckBoxMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem12ActionPerformed
     this.setVisible(false);
        Consultaempleados empleados = new Consultaempleados();
        empleados.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem12ActionPerformed

    private void jCheckBoxMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem10ActionPerformed
    this.setVisible(false);
        consultasucursales sucursal = new consultasucursales();
        sucursal.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem10ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
    this.setVisible(false);
        consultaconductores conductores = new consultaconductores();
        conductores.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void txtcedulaclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedulaclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedulaclienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receptor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem Consultaempleados;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnmostrar;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JButton btnvolver;
    private javax.swing.JCheckBoxMenuItem consultaconductores;
    private javax.swing.JCheckBoxMenuItem consultatransporte;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem10;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem11;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem12;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem7;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu mnconductor;
    private javax.swing.JMenu mnequipo;
    private javax.swing.JMenuItem mniemconductor;
    private javax.swing.JMenuItem mnitemcliente;
    private javax.swing.JMenuItem mnitemequipo;
    private javax.swing.JMenuItem mnitempaquete;
    private javax.swing.JMenuItem mnitemreceptor;
    private javax.swing.JMenuItem mnitemsalir;
    private javax.swing.JMenuItem mnitemsucursal;
    private javax.swing.JMenuItem mnitemtransporte;
    private javax.swing.JMenuItem mnitemusuario;
    private javax.swing.JMenu mnpaquete;
    private javax.swing.JMenu mnsalir;
    private javax.swing.JMenu mnsucursal;
    private javax.swing.JMenu mntransporte;
    private javax.swing.JMenu mnusuario;
    private javax.swing.JPanel panelingresar;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcedulacliente;
    private javax.swing.JTextField txtcodigopostal;
    private javax.swing.JTextField txtdomicilio;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtidreceptor;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnumerocasa;
    private javax.swing.JTextField txtprovincia;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
