/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;


import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

/**
 *
 * @author maria
 */
public class Registro_empleados extends javax.swing.JFrame {

    /**
     * Creates new form Registro_empleados
     */
    public Registro_empleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem8 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        txtidempleado = new javax.swing.JTextField();
        txtnombrecompleto = new javax.swing.JTextField();
        txtedad = new javax.swing.JTextField();
        txtfechanacimiento = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        txthorariodetrabajo = new javax.swing.JTextField();
        txtcargo = new javax.swing.JTextField();
        txttiposeguro = new javax.swing.JTextField();
        txttiposueldo = new javax.swing.JTextField();
        txtsueldo = new javax.swing.JTextField();
        txtfechaingreso = new javax.swing.JTextField();
        txtestado = new javax.swing.JTextField();
        btnvolver = new javax.swing.JButton();
        btnregistrar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btnmostrar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        txtsucursalid = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnusuario = new javax.swing.JMenu();
        mnitemusuario = new javax.swing.JMenuItem();
        mnpaquete = new javax.swing.JMenu();
        mnitempaquete = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnitemreceptor = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnitemcliente = new javax.swing.JMenuItem();
        mntransporte = new javax.swing.JMenu();
        mnitemtransporte = new javax.swing.JMenuItem();
        mnequipo = new javax.swing.JMenu();
        mnitemequipo = new javax.swing.JMenuItem();
        mnsucursal = new javax.swing.JMenu();
        mnitemsucursal = new javax.swing.JMenuItem();
        mnconductor = new javax.swing.JMenu();
        mniemconductor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem7 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem8 = new javax.swing.JCheckBoxMenuItem();
        consultatransporte = new javax.swing.JCheckBoxMenuItem();
        consultaconductores = new javax.swing.JCheckBoxMenuItem();
        Consultaempleados = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem11 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem12 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem10 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        mnsalir = new javax.swing.JMenu();
        mnitemsalir = new javax.swing.JMenuItem();

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Toque el botón mostrar para ver todos los empleados.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 18))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(737, Short.MAX_VALUE))
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese los siguientes datos para registrar al empleado.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 18))); // NOI18N

        txtidempleado.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        txtidempleado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Id empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N
        txtidempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidempleadoActionPerformed(evt);
            }
        });

        txtnombrecompleto.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        txtnombrecompleto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre completo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N

        txtedad.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        txtedad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N
        txtedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtedadActionPerformed(evt);
            }
        });

        txtfechanacimiento.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        txtfechanacimiento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha de nacimiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N

        txttelefono.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        txttelefono.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Teléfono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N

        txtcedula.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        txtcedula.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cédula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N
        txtcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedulaActionPerformed(evt);
            }
        });

        txthorariodetrabajo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        txthorariodetrabajo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Horario de trabajo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N
        txthorariodetrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthorariodetrabajoActionPerformed(evt);
            }
        });

        txtcargo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        txtcargo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cargo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N
        txtcargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcargoActionPerformed(evt);
            }
        });

        txttiposeguro.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        txttiposeguro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de seguro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N

        txttiposueldo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        txttiposueldo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de sueldo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N

        txtsueldo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        txtsueldo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sueldo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N
        txtsueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsueldoActionPerformed(evt);
            }
        });

        txtfechaingreso.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        txtfechaingreso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha de ingreso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N
        txtfechaingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechaingresoActionPerformed(evt);
            }
        });

        txtestado.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        txtestado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N
        txtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestadoActionPerformed(evt);
            }
        });

        btnvolver.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btnvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/previous.png"))); // NOI18N
        btnvolver.setText("Volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        btnregistrar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });

        btnactualizar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btnmostrar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btnmostrar.setText("Mostrar");
        btnmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarActionPerformed(evt);
            }
        });

        btneliminar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnbuscar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa.png"))); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        txtsucursalid.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        txtsucursalid.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Id de la sucursal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N
        txtsucursalid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsucursalidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtnombrecompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtidempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnbuscar))
                        .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtfechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txthorariodetrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txttiposeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txttiposueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtsueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtfechaingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtsucursalid, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnvolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnregistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnactualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnmostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneliminar)))
                .addGap(120, 120, 120))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbuscar)
                    .addComponent(txtidempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnombrecompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txthorariodetrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsucursalid, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttiposeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttiposueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfechaingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btneliminar)
                    .addComponent(btnmostrar)
                    .addComponent(btnactualizar)
                    .addComponent(btnregistrar)
                    .addComponent(btnvolver))
                .addGap(156, 156, 156))
        );

        jScrollPane2.setViewportView(jPanel1);

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 36)); // NOI18N
        jLabel1.setText("Registro Empleado.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        mnusuario.setBackground(new java.awt.Color(255, 204, 204));
        mnusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userLabel.png"))); // NOI18N
        mnusuario.setText("Usuario");
        mnusuario.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemusuario.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userLabel.png"))); // NOI18N
        mnitemusuario.setText("Registro de usuario");
        mnusuario.add(mnitemusuario);

        jMenuBar1.add(mnusuario);

        mnpaquete.setBackground(new java.awt.Color(153, 204, 255));
        mnpaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/box.png"))); // NOI18N
        mnpaquete.setText("Paquete");
        mnpaquete.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitempaquete.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitempaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/box.png"))); // NOI18N
        mnitempaquete.setText("Registro de paquete");
        mnpaquete.add(mnitempaquete);

        jMenuBar1.add(mnpaquete);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/receiver.png"))); // NOI18N
        jMenu3.setText("Receptor");
        jMenu3.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemreceptor.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemreceptor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/receiver.png"))); // NOI18N
        mnitemreceptor.setText("Registrar receptor");
        jMenu3.add(mnitemreceptor);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-avatar.png"))); // NOI18N
        jMenu4.setText("Cliente");
        jMenu4.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemcliente.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-avatar.png"))); // NOI18N
        mnitemcliente.setText("Registrar cliente");
        jMenu4.add(mnitemcliente);

        jMenuBar1.add(jMenu4);

        mntransporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/truck.png"))); // NOI18N
        mntransporte.setText("Transporte");
        mntransporte.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemtransporte.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemtransporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/truck.png"))); // NOI18N
        mnitemtransporte.setText("Registrar un nuevo transporte");
        mntransporte.add(mnitemtransporte);

        jMenuBar1.add(mntransporte);

        mnequipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/computer.png"))); // NOI18N
        mnequipo.setText("Equipo");
        mnequipo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemequipo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemequipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/computer.png"))); // NOI18N
        mnitemequipo.setText("Registrar un nuevo equipo al inventario");
        mnequipo.add(mnitemequipo);

        jMenuBar1.add(mnequipo);

        mnsucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/office.png"))); // NOI18N
        mnsucursal.setText("Sucursal");
        mnsucursal.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemsucursal.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemsucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/office.png"))); // NOI18N
        mnitemsucursal.setText("Registrar nueva sucursal.");
        mnsucursal.add(mnitemsucursal);

        jMenuBar1.add(mnsucursal);

        mnconductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/driver.png"))); // NOI18N
        mnconductor.setText("Conductores");
        mnconductor.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mniemconductor.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mniemconductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/driver.png"))); // NOI18N
        mniemconductor.setText("Registrar un nuevo conductor.");
        mnconductor.add(mniemconductor);

        jMenuBar1.add(mnconductor);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pay.png"))); // NOI18N
        jMenu2.setText("Pago");
        jMenu2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        jRadioButtonMenuItem2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Registro de pago.");
        jRadioButtonMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pay.png"))); // NOI18N
        jMenu2.add(jRadioButtonMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/operator.png"))); // NOI18N
        jMenu1.setText("consultaequipo");
        jMenu1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Consultausuario");
        jCheckBoxMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userLabel.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("Consultacliente");
        jCheckBoxMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-avatar.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem3);

        jCheckBoxMenuItem5.setSelected(true);
        jCheckBoxMenuItem5.setText("Consultafactura");
        jCheckBoxMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/invoice.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem5);

        jCheckBoxMenuItem7.setSelected(true);
        jCheckBoxMenuItem7.setText("Consultacotizacion");
        jCheckBoxMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bill.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem7);

        jCheckBoxMenuItem8.setSelected(true);
        jCheckBoxMenuItem8.setText("Consultaequipo");
        jCheckBoxMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/computer.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem8);

        consultatransporte.setSelected(true);
        consultatransporte.setText("consultapaquete");
        consultatransporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/box.png"))); // NOI18N
        jMenu1.add(consultatransporte);

        consultaconductores.setSelected(true);
        consultaconductores.setText("Consultatransporte");
        consultaconductores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/truck.png"))); // NOI18N
        jMenu1.add(consultaconductores);

        Consultaempleados.setSelected(true);
        Consultaempleados.setText("Consultapago");
        Consultaempleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pay.png"))); // NOI18N
        jMenu1.add(Consultaempleados);

        jCheckBoxMenuItem11.setSelected(true);
        jCheckBoxMenuItem11.setText("consultapaquetesenelinventario");
        jCheckBoxMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/box.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem11);

        jCheckBoxMenuItem12.setSelected(true);
        jCheckBoxMenuItem12.setText("consultaempleados");
        jCheckBoxMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-avatar.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem12);

        jCheckBoxMenuItem10.setSelected(true);
        jCheckBoxMenuItem10.setText("consultasucursal");
        jCheckBoxMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/office.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem10);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("consultaconductores");
        jCheckBoxMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/driver.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem1);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Consulta receptores.");
        jRadioButtonMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/receiver.png"))); // NOI18N
        jMenu1.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu1);

        mnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        mnsalir.setText("Salir");
        mnsalir.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemsalir.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        mnitemsalir.setText("Salir.");
        mnsalir.add(mnitemsalir);

        jMenuBar1.add(mnsalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
         Conexion mysql = new Conexion();
    java.sql.Connection cn = mysql.Conectar();

    String idempleado = txtidempleado.getText();

    String query = "SELECT * FROM empleados WHERE EmpleadoID=?";

    try (PreparedStatement ps = cn.prepareStatement(query)) {
        ps.setString(1, idempleado);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            txtnombrecompleto.setText(rs.getString("nombrecompleto"));
            txtedad.setText(rs.getString("edad"));
            txtfechanacimiento.setText(rs.getString("fechanacimiento"));
            txttelefono.setText(rs.getString("telefono"));
            txtcedula.setText(rs.getString("cedula"));
            txthorariodetrabajo.setText(rs.getString("horariotrabajo"));
            txtcargo.setText(rs.getString("cargo"));
            txtsucursalid.setText(rs.getString("SucursalId"));
            txttiposeguro.setText(rs.getString("tiposeguro"));
            txttiposueldo.setText(rs.getString("tiposueldo"));
            txtsueldo.setText(rs.getString("sueldo"));
            txtfechaingreso.setText(rs.getString("fechaingreso"));
            txtestado.setText(rs.getString("estado"));
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("EmpleadoID");
            model.addColumn("Nombre Completo");
            model.addColumn("Edad");
            model.addColumn("Fecha Nacimiento");
            model.addColumn("Teléfono");
            model.addColumn("Cédula");
            model.addColumn("Horario de Trabajo");
            model.addColumn("Cargo");
            model.addColumn("SucursalId");
            model.addColumn("Tipo de Seguro");
            model.addColumn("Tipo de Sueldo");
            model.addColumn("Sueldo");
            model.addColumn("Fecha Ingreso");
            model.addColumn("Estado");

          
            model.addRow(new Object[]{
                rs.getString("EmpleadoID"),
                rs.getString("nombrecompleto"),
                rs.getString("edad"),
                rs.getString("fechanacimiento"),
                rs.getString("telefono"),
                rs.getString("cedula"),
                rs.getString("horariotrabajo"),
                rs.getString("cargo"),
                rs.getString("SucursalId"),
                rs.getString("tiposeguro"),
                rs.getString("tiposueldo"),
                rs.getString("sueldo"),
                rs.getString("fechaingreso"),
                rs.getString("estado")
            });

            
            jTable1.setModel(model);
        } else {
            JOptionPane.showMessageDialog(null, "Empleado no encontrado.");
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error al buscar el empleado: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        Conexion mysql = new Conexion();
        java.sql.Connection cn = mysql.Conectar();

        try {
            int EmpleadoID = Integer.parseInt(txtidempleado.getText());

            String query = "update empleados set Estado = 'Inactivo' where EmpleadoID = ?";
            try (PreparedStatement ps = cn.prepareStatement(query)) {
                ps.setInt(1, EmpleadoID);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Estado del usuario actualizado a 'Inactivo' correctamente.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El ID del rusuario debe ser un número válido.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No se pudo actualizar el estado: " + e.getMessage());
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarActionPerformed
        Conexion mysql = new Conexion();
        java.sql.Connection cn = mysql.Conectar();

        String query = "SELECT * FROM empleados";
        DefaultTableModel model = new DefaultTableModel();
            model.addColumn("EmpleadoID");
            model.addColumn("Nombre Completo");
            model.addColumn("Edad");
            model.addColumn("Fecha Nacimiento");
            model.addColumn("Teléfono");
            model.addColumn("Cédula");
            model.addColumn("Horario de Trabajo");
            model.addColumn("Cargo");
            model.addColumn("SucursalId");
            model.addColumn("Tipo de Seguro");
            model.addColumn("Tipo de Sueldo");
            model.addColumn("Sueldo");
            model.addColumn("Fecha Ingreso");
            model.addColumn("Estado");

        try (PreparedStatement ps = cn.prepareStatement(query); ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                model.addRow(new Object[]{
                rs.getString("EmpleadoID"),
                rs.getString("nombrecompleto"),
                rs.getString("edad"),
                rs.getString("fechanacimiento"),
                rs.getString("telefono"),
                rs.getString("cedula"),
                rs.getString("horariotrabajo"),
                rs.getString("cargo"),
                rs.getString("SucursalId"),
                rs.getString("tiposeguro"),
                rs.getString("tiposueldo"),
                rs.getString("sueldo"),
                rs.getString("fechaingreso"),
                rs.getString("estado")
                });
            }
            jTable1.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al mostrar los empleados: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnmostrarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        Conexion mysql = new Conexion();
        java.sql.Connection cn = mysql.Conectar();

        int idempleado = Integer.parseInt(txtidempleado.getText());
        String nombrecompleto = txtnombrecompleto.getText();
        String edad = txtedad.getText();
        String fechanacimiento = txtfechanacimiento.getText();
        String telefono = txttelefono.getText();
        String cedula = txtcedula.getText();
        String horariodetrabajo = txthorariodetrabajo.getText();
        String cargo = txtcargo.getText();
        int SucursalID = Integer.parseInt(txtsucursalid.getText());
        String tiposeguro = txttiposeguro.getText();
        String tiposueldo = txttiposueldo.getText();
        String sueldo = txtsueldo.getText();
        String fechaingreso = txtfechaingreso.getText();
        String estado = txtestado.getText();

        String query = "UPDATE empleados SET nombrecompleto=?, edad=?, fechanacimiento=?, telefono=?, cedula=?, horariotrabajo=?, cargo=?, SucursalId=?,  tiposeguro=?, tiposueldo=?, sueldo=?, fechaingreso=?, estado=? WHERE empleadoID=?";

        try (PreparedStatement ps = cn.prepareStatement(query)) {
            ps.setString(1, nombrecompleto);
            ps.setString(2, edad);
            ps.setString(3, fechanacimiento);
            ps.setString(4, telefono);
            ps.setString(5, cedula);
            ps.setString(6, horariodetrabajo);
            ps.setString(7, cargo);
            ps.setInt(8, SucursalID);
            ps.setString(9, tiposeguro);
            ps.setString(10, tiposueldo);
            ps.setString(11, sueldo);
            ps.setString(12, fechaingreso);
            ps.setString(13, estado);
            ps.setInt(14, idempleado);


            int result = ps.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Empleado actualizado exitosamente.");
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar el empleado.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al actualizar el empleado: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        Conexion mysql = new Conexion();
        java.sql.Connection cn = mysql.Conectar();

        String idempleado = txtidempleado.getText();
        String nombrecompleto = txtnombrecompleto.getText();
        String edad = txtedad.getText();
        String fechanacimiento = txtfechanacimiento.getText();
        String telefono = txttelefono.getText();
        String cedula = txtcedula.getText();
        String horariodetrabajo = txthorariodetrabajo.getText();
        String cargo = txtcargo.getText();
        String SucursalID = txtsucursalid.getText();
        String tiposeguro = txttiposeguro.getText();
        String tiposueldo = txttiposueldo.getText();
        String sueldo = txtsueldo.getText();
        String fechaingreso = txtfechaingreso.getText();
        String estado = txtestado.getText();

        String query = "INSERT INTO empleados (EmpleadoID, nombrecompleto, edad, fechanacimiento, telefono, cedula, horariotrabajo, cargo, sucursalId, tiposeguro, tiposueldo, sueldo, fechaingreso, estado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?)";

        try (PreparedStatement ps = cn.prepareStatement(query)) {
            ps.setString(1, idempleado);
            ps.setString(2, nombrecompleto);
            ps.setString(3, edad);
            ps.setString(4, fechanacimiento);
            ps.setString(5, telefono);
            ps.setString(6, cedula);
            ps.setString(7, horariodetrabajo);
            ps.setString(8, cargo);
            ps.setString(9, SucursalID);
            ps.setString(10, tiposeguro);
            ps.setString(11, tiposueldo);
            ps.setString(12, sueldo);
            ps.setString(13, fechaingreso);
            ps.setString(14, estado);

            int result = ps.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Empleado registrado exitosamente.");
            } else {
                JOptionPane.showMessageDialog(null, "Error al registrar el empleado.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al registrar el empleado: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        this.setVisible(false);
        Opciones opcion = new Opciones();
        opcion.setVisible(true);
    }//GEN-LAST:event_btnvolverActionPerformed

    private void txtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoActionPerformed

    private void txtfechaingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechaingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechaingresoActionPerformed

    private void txtsueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsueldoActionPerformed

    private void txtcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedulaActionPerformed

    private void txtidempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidempleadoActionPerformed

    private void txtcargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcargoActionPerformed

    private void txthorariodetrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthorariodetrabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthorariodetrabajoActionPerformed

    private void txtedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtedadActionPerformed

    private void txtsucursalidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsucursalidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsucursalidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem Consultaempleados;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnmostrar;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JButton btnvolver;
    private javax.swing.JCheckBoxMenuItem consultaconductores;
    private javax.swing.JCheckBoxMenuItem consultatransporte;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem10;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem11;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem12;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem7;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu mnconductor;
    private javax.swing.JMenu mnequipo;
    private javax.swing.JMenuItem mniemconductor;
    private javax.swing.JMenuItem mnitemcliente;
    private javax.swing.JMenuItem mnitemequipo;
    private javax.swing.JMenuItem mnitempaquete;
    private javax.swing.JMenuItem mnitemreceptor;
    private javax.swing.JMenuItem mnitemsalir;
    private javax.swing.JMenuItem mnitemsucursal;
    private javax.swing.JMenuItem mnitemtransporte;
    private javax.swing.JMenuItem mnitemusuario;
    private javax.swing.JMenu mnpaquete;
    private javax.swing.JMenu mnsalir;
    private javax.swing.JMenu mnsucursal;
    private javax.swing.JMenu mntransporte;
    private javax.swing.JMenu mnusuario;
    private javax.swing.JTextField txtcargo;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtfechaingreso;
    private javax.swing.JTextField txtfechanacimiento;
    private javax.swing.JTextField txthorariodetrabajo;
    private javax.swing.JTextField txtidempleado;
    private javax.swing.JTextField txtnombrecompleto;
    private javax.swing.JTextField txtsucursalid;
    private javax.swing.JTextField txtsueldo;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txttiposeguro;
    private javax.swing.JTextField txttiposueldo;
    // End of variables declaration//GEN-END:variables
}
