/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maria
 */
public class Registro_equipo extends javax.swing.JFrame {

    /**
     * Creates new form Registro_equipo
     */
    public Registro_equipo() {
        initComponents();
         Conexion mysql = new Conexion();
        java.sql.Connection cn = mysql.Conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtnombre = new javax.swing.JTextField();
        txtnumeroserie = new javax.swing.JTextField();
        txtcantidad = new javax.swing.JTextField();
        txtpeso = new javax.swing.JTextField();
        txtutilidad = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnregistrar = new javax.swing.JButton();
        txtidequipo = new javax.swing.JTextField();
        txtestado = new javax.swing.JTextField();
        btnactualizar = new javax.swing.JButton();
        btnmostrar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnusuario = new javax.swing.JMenu();
        mnitemusuario = new javax.swing.JMenuItem();
        mnpaquete = new javax.swing.JMenu();
        mnitempaquete = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnitemreceptor = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnitemcliente = new javax.swing.JMenuItem();
        mntransporte = new javax.swing.JMenu();
        mnitemtransporte = new javax.swing.JMenuItem();
        mnequipo = new javax.swing.JMenu();
        mnitemequipo = new javax.swing.JMenuItem();
        mnsucursal = new javax.swing.JMenu();
        mnitemsucursal = new javax.swing.JMenuItem();
        mnconductor = new javax.swing.JMenu();
        mniemconductor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem7 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem8 = new javax.swing.JCheckBoxMenuItem();
        consultatransporte = new javax.swing.JCheckBoxMenuItem();
        consultaconductores = new javax.swing.JCheckBoxMenuItem();
        Consultaempleados = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem11 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem12 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem10 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        mnsalir = new javax.swing.JMenu();
        mnitemsalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese los datos para registar un equipo al inventario.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 18))); // NOI18N

        txtnombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre del equipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        txtnumeroserie.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Número de serie", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N
        txtnumeroserie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumeroserieActionPerformed(evt);
            }
        });

        txtcantidad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N

        txtpeso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Peso KG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N

        txtutilidad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Utilidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N

        txtdescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripción", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N
        txtdescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescripcionActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/previous.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnregistrar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });

        txtidequipo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Id del equipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N
        txtidequipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidequipoActionPerformed(evt);
            }
        });

        txtestado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N
        txtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestadoActionPerformed(evt);
            }
        });

        btnactualizar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btnmostrar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btnmostrar.setText("Mostrar");
        btnmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarActionPerformed(evt);
            }
        });

        btneliminar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnbuscar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa.png"))); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtutilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpeso, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumeroserie, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtidequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnregistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnactualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btneliminar))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidequipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnumeroserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtutilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnregistrar)
                    .addComponent(btnactualizar)
                    .addComponent(btnmostrar)
                    .addComponent(btneliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Toque el botón mostrar para ver todos los datos del inventario de equipos.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 18))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        titulo.setBackground(new java.awt.Color(255, 204, 204));
        titulo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 22)); // NOI18N
        titulo.setText("Información del Inventario de equipos.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(titulo)
                .addContainerGap())
        );

        mnusuario.setBackground(new java.awt.Color(255, 204, 204));
        mnusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userLabel.png"))); // NOI18N
        mnusuario.setText("Usuario");
        mnusuario.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemusuario.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userLabel.png"))); // NOI18N
        mnitemusuario.setText("Registro de usuario");
        mnusuario.add(mnitemusuario);

        jMenuBar1.add(mnusuario);

        mnpaquete.setBackground(new java.awt.Color(153, 204, 255));
        mnpaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/box.png"))); // NOI18N
        mnpaquete.setText("Paquete");
        mnpaquete.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitempaquete.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitempaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/box.png"))); // NOI18N
        mnitempaquete.setText("Registro de paquete");
        mnpaquete.add(mnitempaquete);

        jMenuBar1.add(mnpaquete);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/receiver.png"))); // NOI18N
        jMenu3.setText("Receptor");
        jMenu3.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemreceptor.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemreceptor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/receiver.png"))); // NOI18N
        mnitemreceptor.setText("Registrar receptor");
        jMenu3.add(mnitemreceptor);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-avatar.png"))); // NOI18N
        jMenu4.setText("Cliente");
        jMenu4.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemcliente.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-avatar.png"))); // NOI18N
        mnitemcliente.setText("Registrar cliente");
        jMenu4.add(mnitemcliente);

        jMenuBar1.add(jMenu4);

        mntransporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/truck.png"))); // NOI18N
        mntransporte.setText("Transporte");
        mntransporte.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemtransporte.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemtransporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/truck.png"))); // NOI18N
        mnitemtransporte.setText("Registrar un nuevo transporte");
        mntransporte.add(mnitemtransporte);

        jMenuBar1.add(mntransporte);

        mnequipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/computer.png"))); // NOI18N
        mnequipo.setText("Equipo");
        mnequipo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemequipo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemequipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/computer.png"))); // NOI18N
        mnitemequipo.setText("Registrar un nuevo equipo al inventario");
        mnequipo.add(mnitemequipo);

        jMenuBar1.add(mnequipo);

        mnsucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/office.png"))); // NOI18N
        mnsucursal.setText("Sucursal");
        mnsucursal.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemsucursal.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemsucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/office.png"))); // NOI18N
        mnitemsucursal.setText("Registrar nueva sucursal.");
        mnsucursal.add(mnitemsucursal);

        jMenuBar1.add(mnsucursal);

        mnconductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/driver.png"))); // NOI18N
        mnconductor.setText("Conductores");
        mnconductor.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mniemconductor.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mniemconductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/driver.png"))); // NOI18N
        mniemconductor.setText("Registrar un nuevo conductor.");
        mnconductor.add(mniemconductor);

        jMenuBar1.add(mnconductor);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pay.png"))); // NOI18N
        jMenu2.setText("Pago");
        jMenu2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        jRadioButtonMenuItem2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Registro de pago.");
        jRadioButtonMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pay.png"))); // NOI18N
        jMenu2.add(jRadioButtonMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/operator.png"))); // NOI18N
        jMenu1.setText("consultaequipo");
        jMenu1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Consultausuario");
        jCheckBoxMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userLabel.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("Consultacliente");
        jCheckBoxMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-avatar.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem3);

        jCheckBoxMenuItem5.setSelected(true);
        jCheckBoxMenuItem5.setText("Consultafactura");
        jCheckBoxMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/invoice.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem5);

        jCheckBoxMenuItem7.setSelected(true);
        jCheckBoxMenuItem7.setText("Consultacotizacion");
        jCheckBoxMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bill.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem7);

        jCheckBoxMenuItem8.setSelected(true);
        jCheckBoxMenuItem8.setText("Consultaequipo");
        jCheckBoxMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/computer.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem8);

        consultatransporte.setSelected(true);
        consultatransporte.setText("consultapaquete");
        consultatransporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/box.png"))); // NOI18N
        jMenu1.add(consultatransporte);

        consultaconductores.setSelected(true);
        consultaconductores.setText("Consultatransporte");
        consultaconductores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/truck.png"))); // NOI18N
        jMenu1.add(consultaconductores);

        Consultaempleados.setSelected(true);
        Consultaempleados.setText("Consultapago");
        Consultaempleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pay.png"))); // NOI18N
        jMenu1.add(Consultaempleados);

        jCheckBoxMenuItem11.setSelected(true);
        jCheckBoxMenuItem11.setText("consultapaquetesenelinventario");
        jCheckBoxMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/box.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem11);

        jCheckBoxMenuItem12.setSelected(true);
        jCheckBoxMenuItem12.setText("consultaempleados");
        jCheckBoxMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-avatar.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem12);

        jCheckBoxMenuItem10.setSelected(true);
        jCheckBoxMenuItem10.setText("consultasucursal");
        jCheckBoxMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/office.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem10);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("consultaconductores");
        jCheckBoxMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/driver.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem1);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Consulta receptores.");
        jRadioButtonMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/receiver.png"))); // NOI18N
        jMenu1.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu1);

        mnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        mnsalir.setText("Salir");
        mnsalir.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemsalir.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        mnitemsalir.setText("Salir.");
        mnsalir.add(mnitemsalir);

        jMenuBar1.add(mnsalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescripcionActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
        Opciones opcion = new Opciones();
        opcion.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        Conexion mysql = new Conexion();
        java.sql.Connection cn = mysql.Conectar();

        
        int EquipoID = Integer.parseInt(txtidequipo.getText());
        String nombre = txtnombre.getText();
        String numeroserie = txtnumeroserie.getText();
        int cantidad = Integer.parseInt(txtcantidad.getText());
        float pesokg = Float.parseFloat(txtpeso.getText());
        String utilidad = txtutilidad.getText();
        String descripcion = txtdescripcion.getText();
        String Estado = txtestado.getText();
        
        String inventario_equipos = "INSERT INTO inventario_equipos(EquipoID, NombreEquipo, NumeroSerie, Cantidad, PesoKG, Utilidad, Descripcion, Estado) VALUES(?, ?, ?, ?, ?, ?, ?,?)";
        try (PreparedStatement ps = cn.prepareStatement(inventario_equipos)){
            ps.setInt(1, EquipoID);
            ps.setString(2, nombre);
             ps.setString(3, numeroserie);
            ps.setInt(4, cantidad);
            ps.setFloat(5, pesokg);
            ps.setString(6, utilidad);
            ps.setString(7, descripcion);
            ps.setString(8, Estado);
         
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos guardados correctamente.");
        
        }
        catch (SQLException e){
                JOptionPane.showMessageDialog(null, "No se pudo guardar el equipo" + e.getMessage());
                
        }
      
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void txtidequipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidequipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidequipoActionPerformed

    private void txtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        Conexion mysql=new Conexion();
        java.sql.Connection cn = mysql.Conectar();
        int EquipoID = Integer.parseInt(txtidequipo.getText());
        String NombreEquipo = txtnombre.getText();
        String NumeroSerie = txtnumeroserie.getText();
        int cantidad = Integer.parseInt(txtcantidad.getText());
        Float pesoKG = Float.parseFloat(txtpeso.getText());
        String utilidad = txtutilidad.getText();
        String descripcion = txtdescripcion.getText();
        String Estado = txtestado.getText();

String query="Update inventario_equipos set  EquipoId=?, NombreEquipo=?, NumeroSerie=?, Cantidad=?, pesoKG=?, Utilidad=?, descripcion=?, Estado=? where EquipoId=? ";
try(PreparedStatement ps=cn.prepareStatement(query))  {
  
            ps.setInt(1, EquipoID);
            ps.setString(2, NombreEquipo);
            ps.setString(3, NumeroSerie);
            ps.setInt(4, cantidad);
            ps.setFloat(5, pesoKG);
            ps.setString(6, utilidad);
            ps.setString(7, descripcion);
            ps.setString(8, Estado);
            ps.setInt(9, EquipoID);
   
  
    
     ps.executeUpdate();
     JOptionPane.showMessageDialog(null, "datos actualizados correctamente");
     
}
catch(SQLException e){
    JOptionPane.showMessageDialog(null, "no se pudo actualizar correctamente"+e.getMessage());
}      
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarActionPerformed
         
         Conexion mysql = new Conexion();
        java.sql.Connection cn = mysql.Conectar();
        
        ResultSet rs;
        PreparedStatement ps;
   
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            jTable1.setModel(modelo);
            
            ps=cn.prepareStatement("SELECT * FROM INVENTARIO_EQUIPOS");
            rs=ps.executeQuery();
                        
            java.sql.ResultSetMetaData rsMd =rs.getMetaData();
            int cColumnas = rsMd.getColumnCount();
            modelo.addColumn("EquipoID");
            modelo.addColumn("NombreEquipo");
            modelo.addColumn("Numeroserie");
            modelo.addColumn("Cantidad");
            modelo.addColumn("PesoKG");
            modelo.addColumn("Utilidad");
            modelo.addColumn("Descripcion");
            modelo.addColumn("Estado");

            
            while (rs.next()){
                Object[] filas = new Object [cColumnas];
                for (int i=0; i<cColumnas;i++){
                    filas[i]=rs.getObject(i+1);
                }
                modelo.addRow(filas);
                    
            }
    
         }catch(SQLException e){
  
                JOptionPane.showMessageDialog(null, "No se pudieron mostrar los datos  " + e.getMessage());
   }
    }//GEN-LAST:event_btnmostrarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        Conexion mysql = new Conexion();
    java.sql.Connection cn = mysql.Conectar();

    try {
        int EquipoID = Integer.parseInt(txtidequipo.getText());
        
        String query = "update inventario_equipos set Estado = 'Inactivo' where EquipoID = ?";
        try (PreparedStatement ps = cn.prepareStatement(query)) {
            ps.setInt(1, EquipoID);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Estado del equipo actualizado a 'Inactivo' correctamente.");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "El ID del equipo debe ser un número válido.");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "No se pudo actualizar el estado: " + e.getMessage());
    }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
         Conexion mysql = new Conexion();
        java.sql.Connection cn = mysql.Conectar();
        ResultSet rs;
        PreparedStatement ps;

    try {
        int EquipoID = Integer.parseInt(txtidequipo.getText());
        String query = "select * from inventario_equipos where EquipoID = ?";
        ps = cn.prepareStatement(query);
        ps.setInt(1, EquipoID);
        rs = ps.executeQuery();

        if (rs.next()) {
            txtnombre.setText(rs.getString("NombreEquipo"));
            txtnumeroserie.setText(rs.getString("NumeroSerie"));
            txtcantidad.setText(rs.getString("Cantidad"));
            txtpeso.setText(rs.getString("PesoKG"));
            txtutilidad.setText(rs.getString("Utilidad"));
            txtdescripcion.setText(rs.getString("Descripcion"));
            txtestado.setText(rs.getString("Estado"));
        } else {
            JOptionPane.showMessageDialog(null, "Equipo no encontrado.");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al buscar los datos: " + e.getMessage());
    }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtnumeroserieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumeroserieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumeroserieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_equipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem Consultaempleados;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnmostrar;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JCheckBoxMenuItem consultaconductores;
    private javax.swing.JCheckBoxMenuItem consultatransporte;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem10;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem11;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem12;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem7;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu mnconductor;
    private javax.swing.JMenu mnequipo;
    private javax.swing.JMenuItem mniemconductor;
    private javax.swing.JMenuItem mnitemcliente;
    private javax.swing.JMenuItem mnitemequipo;
    private javax.swing.JMenuItem mnitempaquete;
    private javax.swing.JMenuItem mnitemreceptor;
    private javax.swing.JMenuItem mnitemsalir;
    private javax.swing.JMenuItem mnitemsucursal;
    private javax.swing.JMenuItem mnitemtransporte;
    private javax.swing.JMenuItem mnitemusuario;
    private javax.swing.JMenu mnpaquete;
    private javax.swing.JMenu mnsalir;
    private javax.swing.JMenu mnsucursal;
    private javax.swing.JMenu mntransporte;
    private javax.swing.JMenu mnusuario;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtidequipo;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnumeroserie;
    private javax.swing.JTextField txtpeso;
    private javax.swing.JTextField txtutilidad;
    // End of variables declaration//GEN-END:variables
}
