/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;


import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maria
 */
public class Registro_conductores extends javax.swing.JFrame {

    /**
     *
     */
    Conexion mysql = new Conexion();
   java.sql.Connection cn = mysql.Conectar();
    public Registro_conductores() {
        initComponents();
    }
     private void limpiarCampos() {
        txtidconductor.setText("");
        txtidempleado.setText("");
        txtnombre.setText("");
        txttipolicencia.setText("");
        txtvehiculo.setText("");
        txtnivelexperiencia.setText("");
        txtestado.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelfondo = new javax.swing.JPanel();
        btnregistrar = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();
        txtidconductor = new javax.swing.JTextField();
        txttipolicencia = new javax.swing.JTextField();
        txtvehiculo = new javax.swing.JTextField();
        txtnivelexperiencia = new javax.swing.JTextField();
        btnactualizar = new javax.swing.JButton();
        btnmostrar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        txtidempleado = new javax.swing.JTextField();
        txtestado = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        txtnombre = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnsalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnusuario = new javax.swing.JMenu();
        mnitemusuario = new javax.swing.JMenuItem();
        mnpaquete = new javax.swing.JMenu();
        mnitempaquete = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnitemreceptor = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnitemcliente = new javax.swing.JMenuItem();
        mntransporte = new javax.swing.JMenu();
        mnitemtransporte = new javax.swing.JMenuItem();
        mnequipo = new javax.swing.JMenu();
        mnitemequipo = new javax.swing.JMenuItem();
        mnsucursal = new javax.swing.JMenu();
        mnitemsucursal = new javax.swing.JMenuItem();
        mnconductor = new javax.swing.JMenu();
        mniemconductor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem7 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem8 = new javax.swing.JCheckBoxMenuItem();
        consultatransporte = new javax.swing.JCheckBoxMenuItem();
        consultaconductores = new javax.swing.JCheckBoxMenuItem();
        Consultaempleados = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem11 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem12 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem10 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        mnsalir = new javax.swing.JMenu();
        mnitemsalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelfondo.setBackground(new java.awt.Color(153, 204, 255));
        panelfondo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese la información del conductor.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 18))); // NOI18N

        btnregistrar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });

        btnvolver.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btnvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/previous.png"))); // NOI18N
        btnvolver.setText("Volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        txtidconductor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Id conductor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N

        txttipolicencia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de licencia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N

        txtvehiculo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vehículo que puede conducir", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N

        txtnivelexperiencia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nivel de experiencia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N

        btnactualizar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btnmostrar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btnmostrar.setText("Mostrar");
        btnmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarActionPerformed(evt);
            }
        });

        btneliminar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        txtidempleado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Id empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N

        txtestado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N

        btnbuscar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa.png"))); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        txtnombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N

        javax.swing.GroupLayout panelfondoLayout = new javax.swing.GroupLayout(panelfondo);
        panelfondo.setLayout(panelfondoLayout);
        panelfondoLayout.setHorizontalGroup(
            panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnvolver)
                .addGap(5, 5, 5)
                .addComponent(btnregistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnactualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btneliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelfondoLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttipolicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnivelexperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelfondoLayout.createSequentialGroup()
                        .addComponent(txtidconductor, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnbuscar))
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panelfondoLayout.setVerticalGroup(
            panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidconductor, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtidempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttipolicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtvehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnivelexperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnactualizar)
                    .addComponent(btnmostrar)
                    .addComponent(btneliminar)
                    .addComponent(btnregistrar)
                    .addComponent(btnvolver))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel2.setText("Toque el botón mostrar para ver todos los conductores.");

        btnsalir.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsalir))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsalir)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        jLabel1.setText("Registro de conductores.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        mnusuario.setBackground(new java.awt.Color(255, 204, 204));
        mnusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userLabel.png"))); // NOI18N
        mnusuario.setText("Usuario");
        mnusuario.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemusuario.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userLabel.png"))); // NOI18N
        mnitemusuario.setText("Registro de usuario");
        mnusuario.add(mnitemusuario);

        jMenuBar1.add(mnusuario);

        mnpaquete.setBackground(new java.awt.Color(153, 204, 255));
        mnpaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/box.png"))); // NOI18N
        mnpaquete.setText("Paquete");
        mnpaquete.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitempaquete.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitempaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/box.png"))); // NOI18N
        mnitempaquete.setText("Registro de paquete");
        mnpaquete.add(mnitempaquete);

        jMenuBar1.add(mnpaquete);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/receiver.png"))); // NOI18N
        jMenu3.setText("Receptor");
        jMenu3.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemreceptor.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemreceptor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/receiver.png"))); // NOI18N
        mnitemreceptor.setText("Registrar receptor");
        jMenu3.add(mnitemreceptor);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-avatar.png"))); // NOI18N
        jMenu4.setText("Cliente");
        jMenu4.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemcliente.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-avatar.png"))); // NOI18N
        mnitemcliente.setText("Registrar cliente");
        jMenu4.add(mnitemcliente);

        jMenuBar1.add(jMenu4);

        mntransporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/truck.png"))); // NOI18N
        mntransporte.setText("Transporte");
        mntransporte.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemtransporte.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemtransporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/truck.png"))); // NOI18N
        mnitemtransporte.setText("Registrar un nuevo transporte");
        mntransporte.add(mnitemtransporte);

        jMenuBar1.add(mntransporte);

        mnequipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/computer.png"))); // NOI18N
        mnequipo.setText("Equipo");
        mnequipo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemequipo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemequipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/computer.png"))); // NOI18N
        mnitemequipo.setText("Registrar un nuevo equipo al inventario");
        mnequipo.add(mnitemequipo);

        jMenuBar1.add(mnequipo);

        mnsucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/office.png"))); // NOI18N
        mnsucursal.setText("Sucursal");
        mnsucursal.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemsucursal.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemsucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/office.png"))); // NOI18N
        mnitemsucursal.setText("Registrar nueva sucursal.");
        mnsucursal.add(mnitemsucursal);

        jMenuBar1.add(mnsucursal);

        mnconductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/driver.png"))); // NOI18N
        mnconductor.setText("Conductores");
        mnconductor.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mniemconductor.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mniemconductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/driver.png"))); // NOI18N
        mniemconductor.setText("Registrar un nuevo conductor.");
        mnconductor.add(mniemconductor);

        jMenuBar1.add(mnconductor);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pay.png"))); // NOI18N
        jMenu2.setText("Pago");
        jMenu2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        jRadioButtonMenuItem2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Registro de pago.");
        jRadioButtonMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pay.png"))); // NOI18N
        jMenu2.add(jRadioButtonMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/operator.png"))); // NOI18N
        jMenu1.setText("consultaequipo");
        jMenu1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Consultausuario");
        jCheckBoxMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userLabel.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("Consultacliente");
        jCheckBoxMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-avatar.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem3);

        jCheckBoxMenuItem5.setSelected(true);
        jCheckBoxMenuItem5.setText("Consultafactura");
        jCheckBoxMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/invoice.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem5);

        jCheckBoxMenuItem7.setSelected(true);
        jCheckBoxMenuItem7.setText("Consultacotizacion");
        jCheckBoxMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bill.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem7);

        jCheckBoxMenuItem8.setSelected(true);
        jCheckBoxMenuItem8.setText("Consultaequipo");
        jCheckBoxMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/computer.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem8);

        consultatransporte.setSelected(true);
        consultatransporte.setText("consultapaquete");
        consultatransporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/box.png"))); // NOI18N
        jMenu1.add(consultatransporte);

        consultaconductores.setSelected(true);
        consultaconductores.setText("Consultatransporte");
        consultaconductores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/truck.png"))); // NOI18N
        jMenu1.add(consultaconductores);

        Consultaempleados.setSelected(true);
        Consultaempleados.setText("Consultapago");
        Consultaempleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pay.png"))); // NOI18N
        jMenu1.add(Consultaempleados);

        jCheckBoxMenuItem11.setSelected(true);
        jCheckBoxMenuItem11.setText("consultapaquetesenelinventario");
        jCheckBoxMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/box.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem11);

        jCheckBoxMenuItem12.setSelected(true);
        jCheckBoxMenuItem12.setText("consultaempleados");
        jCheckBoxMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-avatar.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem12);

        jCheckBoxMenuItem10.setSelected(true);
        jCheckBoxMenuItem10.setText("consultasucursal");
        jCheckBoxMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/office.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem10);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("consultaconductores");
        jCheckBoxMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/driver.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem1);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Consulta receptores.");
        jRadioButtonMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/receiver.png"))); // NOI18N
        jMenu1.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu1);

        mnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        mnsalir.setText("Salir");
        mnsalir.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemsalir.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        mnitemsalir.setText("Salir.");
        mnsalir.add(mnitemsalir);

        jMenuBar1.add(mnsalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelfondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        this.setVisible(false);
        Opciones opcion = new Opciones();
        opcion.setVisible(true);
    }//GEN-LAST:event_btnvolverActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        Conexion mysql = new Conexion();
        java.sql.Connection cn = mysql.Conectar();
        
        int ConductorID = Integer.parseInt(txtidconductor.getText());
        int EmpleadoID = Integer.parseInt(txtidempleado.getText());
        String nombre = txtnombre.getText();
        String TipoLicencia = txttipolicencia.getText();
        String vehiculosQuePuedeConducir = txtvehiculo.getText();
        String NivelExperiencia =txtnivelexperiencia.getText();
        String Estado = txtestado.getText();
        
        String registro = "INSERT INTO conductores(ConductorID, EmpleadoID,nombre, TipoLicencia, VehiculosQuePuedeConducir, NivelExperiencia, EStado) VALUES(?, ?, ?, ?, ?,?,?)";
        try (PreparedStatement ps = cn.prepareStatement(registro)){
            ps.setInt(1, ConductorID);
            ps.setInt(2, EmpleadoID);
            ps.setString(3, nombre);
            ps.setString(4, TipoLicencia);
            ps.setString(5, vehiculosQuePuedeConducir);
            ps.setString(6, NivelExperiencia);
            ps.setString(7, Estado);
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos guardados correctamente.");
            limpiarCampos();
        }
        catch (SQLException e){
                JOptionPane.showMessageDialog(null, "No se pudo guardar: " + e.getMessage());
                }
        
        
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
Conexion mysql=new Conexion();
java.sql.Connection cn = mysql.Conectar();
        int ConductorID = Integer.parseInt(txtidconductor.getText());
        int EmpleadoID = Integer.parseInt(txtidempleado.getText());
         String nombre = txtnombre.getText();
        String TipoLicencia = txttipolicencia.getText();
        String vehiculosQuePuedeConducir = txtvehiculo.getText();
        String NivelExperiencia =txtnivelexperiencia.getText();
        String Estado = txtestado.getText();

String query="Update Conductores set  ConductorId=?, EmpleadoID=?,nombre=?, TipoLicencia=?, VehiculosQuePuedeConducir=?, NivelExperiencia=?, Estado=? where ConductorId=? ";
try(PreparedStatement ps=cn.prepareStatement(query))  {
  
            ps.setInt(1, ConductorID);
            ps.setInt(2, EmpleadoID);
              ps.setString(3, nombre);
            ps.setString(4, TipoLicencia);
            ps.setString(5, vehiculosQuePuedeConducir);
            ps.setString(6, NivelExperiencia);
            ps.setString(7, Estado);
            ps.setInt(8, ConductorID);
   
  
    
     ps.executeUpdate();
     JOptionPane.showMessageDialog(null, "datos actualizados correctamente");
     
}
catch(SQLException e){
    JOptionPane.showMessageDialog(null, "no se pudo actualizar correctamente"+e.getMessage());
}      
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarActionPerformed
       ResultSet rs;
   PreparedStatement ps;
   
        try {
            DefaultTableModel modelo = new DefaultTableModel();
            jTable1.setModel(modelo);
            
            ps=cn.prepareStatement("SELECT * FROM CONDUCTORES");
            rs=ps.executeQuery();
                        
            java.sql.ResultSetMetaData rsMd =rs.getMetaData();
            int cColumnas = rsMd.getColumnCount();
            modelo.addColumn("ConductorID");
            modelo.addColumn("EmpleadoID");
            modelo.addColumn("Nombre");
            modelo.addColumn("TipoLicencia");
            modelo.addColumn("Vehiculoquepuedeconducir");
            modelo.addColumn("NivelExperiencia");
            modelo.addColumn("Estado");

            
            while (rs.next()){
                Object[] filas = new Object [cColumnas];
                for (int i=0; i<cColumnas;i++){
                    filas[i]=rs.getObject(i+1);
                }
                modelo.addRow(filas);
                    
            }
    
         }catch(SQLException e){
  
                JOptionPane.showMessageDialog(null, "No se pudieron mostrar los datos  " + e.getMessage());
   }
    }//GEN-LAST:event_btnmostrarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
  Conexion mysql = new Conexion();
    java.sql.Connection cn = mysql.Conectar();

    try {
        int ConductorID = Integer.parseInt(txtidconductor.getText());
        
        String query = "update Conductores set Estado = 'Inactivo' where ConductorID = ?";
        try (PreparedStatement ps = cn.prepareStatement(query)) {
            ps.setInt(1, ConductorID);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Estado del conductor actualizado a 'Inactivo' correctamente.");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "El ID del conductor debe ser un número válido.");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "No se pudo actualizar el estado: " + e.getMessage());
    }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
    ResultSet rs;
    PreparedStatement ps;

    try {
        int ConductorID = Integer.parseInt(txtidconductor.getText());
        String query = "select * from conductores where ConductorID = ?";
        ps = cn.prepareStatement(query);
        ps.setInt(1, ConductorID);
        rs = ps.executeQuery();

        if (rs.next()) {
            txtidempleado.setText(String.valueOf(rs.getInt("EmpleadoID")));
            txtnombre.setText(rs.getString("Nombre"));
            txttipolicencia.setText(rs.getString("TipoLicencia"));
            txtvehiculo.setText(rs.getString("VehiculosQuePuedeConducir"));
            txtnivelexperiencia.setText(rs.getString("NivelExperiencia"));
            txtestado.setText(rs.getString("Estado"));
        } else {
            JOptionPane.showMessageDialog(null, "Conductor no encontrado.");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al buscar los datos: " + e.getMessage());
    }
        
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
    System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_conductores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_conductores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_conductores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_conductores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_conductores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem Consultaempleados;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnmostrar;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btnvolver;
    private javax.swing.JCheckBoxMenuItem consultaconductores;
    private javax.swing.JCheckBoxMenuItem consultatransporte;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem10;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem11;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem12;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem7;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu mnconductor;
    private javax.swing.JMenu mnequipo;
    private javax.swing.JMenuItem mniemconductor;
    private javax.swing.JMenuItem mnitemcliente;
    private javax.swing.JMenuItem mnitemequipo;
    private javax.swing.JMenuItem mnitempaquete;
    private javax.swing.JMenuItem mnitemreceptor;
    private javax.swing.JMenuItem mnitemsalir;
    private javax.swing.JMenuItem mnitemsucursal;
    private javax.swing.JMenuItem mnitemtransporte;
    private javax.swing.JMenuItem mnitemusuario;
    private javax.swing.JMenu mnpaquete;
    private javax.swing.JMenu mnsalir;
    private javax.swing.JMenu mnsucursal;
    private javax.swing.JMenu mntransporte;
    private javax.swing.JMenu mnusuario;
    private javax.swing.JPanel panelfondo;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtidconductor;
    private javax.swing.JTextField txtidempleado;
    private javax.swing.JTextField txtnivelexperiencia;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttipolicencia;
    private javax.swing.JTextField txtvehiculo;
    // End of variables declaration//GEN-END:variables
}
