package Formularios;


import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author maria
 */
public class Registrocliente extends javax.swing.JFrame {

    /**
     * Creates new form Informacionenvio
     */
    Conexion mysql = new Conexion();
   java.sql.Connection cn = mysql.Conectar();
    public Registrocliente() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        txtapellido = new javax.swing.JTextField();
        txtnumerodecasa = new javax.swing.JTextField();
        txtdomicilio = new javax.swing.JTextField();
        txtcodigopostal = new javax.swing.JTextField();
        btnregistrar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        txtnombre = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        btnmostrar = new javax.swing.JButton();
        txtestado = new javax.swing.JTextField();
        btnvolver = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        txtidcliente = new javax.swing.JTextField();
        btneliminar1 = new javax.swing.JButton();
        btnregistrarpaquete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnusuario = new javax.swing.JMenu();
        mnitemusuario = new javax.swing.JMenuItem();
        mnpaquete = new javax.swing.JMenu();
        mnitempaquete = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnitemreceptor = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnitemcliente = new javax.swing.JMenuItem();
        mntransporte = new javax.swing.JMenu();
        mnitemtransporte = new javax.swing.JMenuItem();
        mnequipo = new javax.swing.JMenu();
        mnitemequipo = new javax.swing.JMenuItem();
        mnsucursal = new javax.swing.JMenu();
        mnitemsucursal = new javax.swing.JMenuItem();
        mnconductor = new javax.swing.JMenu();
        mniemconductor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem7 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem8 = new javax.swing.JCheckBoxMenuItem();
        consultatransporte = new javax.swing.JCheckBoxMenuItem();
        consultaconductores = new javax.swing.JCheckBoxMenuItem();
        Consultaempleados = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem11 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem12 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem10 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        mnsalir = new javax.swing.JMenu();
        mnitemsalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        jLabel1.setText("Informaciones de clientes.");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingresar las siguientes informaciones:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 18))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N

        txtapellido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 12))); // NOI18N
        txtapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidoActionPerformed(evt);
            }
        });

        txtnumerodecasa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Número de casa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 12))); // NOI18N
        txtnumerodecasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumerodecasaActionPerformed(evt);
            }
        });

        txtdomicilio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Domicilio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 12))); // NOI18N
        txtdomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdomicilioActionPerformed(evt);
            }
        });

        txtcodigopostal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Código postal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 12))); // NOI18N

        btnregistrar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        btnregistrar.setText("Registrar");
        btnregistrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });

        btnactualizar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        btnactualizar.setText("Actualizar");
        btnactualizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        txtnombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 12))); // NOI18N
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        txttelefono.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Teléfono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 12))); // NOI18N

        btnmostrar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        btnmostrar.setText("Mostrar");
        btnmostrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarActionPerformed(evt);
            }
        });

        txtestado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 12))); // NOI18N
        txtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestadoActionPerformed(evt);
            }
        });

        btnvolver.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        btnvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/previous.png"))); // NOI18N
        btnvolver.setText("Volver");
        btnvolver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        btneliminar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        txtidcliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cédula cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 14))); // NOI18N
        txtidcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidclienteActionPerformed(evt);
            }
        });

        btneliminar1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        btneliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa.png"))); // NOI18N
        btneliminar1.setText("Buscar");
        btneliminar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btneliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminar1ActionPerformed(evt);
            }
        });

        btnregistrarpaquete.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 12)); // NOI18N
        btnregistrarpaquete.setText("Registrar paquete.");
        btnregistrarpaquete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnregistrarpaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarpaqueteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtcodigopostal, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumerodecasa, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addComponent(txttelefono)
                        .addComponent(txtapellido, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnmostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnregistrarpaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnumerodecasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcodigopostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnregistrar)
                            .addComponent(btnactualizar)
                            .addComponent(btnmostrar)
                            .addComponent(btneliminar))
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnvolver)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnregistrarpaquete)
                .addGap(82, 82, 82))
        );

        jScrollPane2.setViewportView(jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de clientes:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 0, 18))); // NOI18N

        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleName("tabla");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        jLabel2.setText("Toque el botón mostrar para ver los datos de todos los clientes.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mnusuario.setBackground(new java.awt.Color(255, 204, 204));
        mnusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userLabel.png"))); // NOI18N
        mnusuario.setText("Usuario");
        mnusuario.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemusuario.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userLabel.png"))); // NOI18N
        mnitemusuario.setText("Registro de usuario");
        mnusuario.add(mnitemusuario);

        jMenuBar1.add(mnusuario);

        mnpaquete.setBackground(new java.awt.Color(153, 204, 255));
        mnpaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/box.png"))); // NOI18N
        mnpaquete.setText("Paquete");
        mnpaquete.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitempaquete.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitempaquete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/box.png"))); // NOI18N
        mnitempaquete.setText("Registro de paquete");
        mnpaquete.add(mnitempaquete);

        jMenuBar1.add(mnpaquete);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/receiver.png"))); // NOI18N
        jMenu3.setText("Receptor");
        jMenu3.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemreceptor.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemreceptor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/receiver.png"))); // NOI18N
        mnitemreceptor.setText("Registrar receptor");
        jMenu3.add(mnitemreceptor);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-avatar.png"))); // NOI18N
        jMenu4.setText("Cliente");
        jMenu4.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemcliente.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-avatar.png"))); // NOI18N
        mnitemcliente.setText("Registrar cliente");
        jMenu4.add(mnitemcliente);

        jMenuBar1.add(jMenu4);

        mntransporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/truck.png"))); // NOI18N
        mntransporte.setText("Transporte");
        mntransporte.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemtransporte.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemtransporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/truck.png"))); // NOI18N
        mnitemtransporte.setText("Registrar un nuevo transporte");
        mntransporte.add(mnitemtransporte);

        jMenuBar1.add(mntransporte);

        mnequipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/computer.png"))); // NOI18N
        mnequipo.setText("Equipo");
        mnequipo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemequipo.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemequipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/computer.png"))); // NOI18N
        mnitemequipo.setText("Registrar un nuevo equipo al inventario");
        mnequipo.add(mnitemequipo);

        jMenuBar1.add(mnequipo);

        mnsucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/office.png"))); // NOI18N
        mnsucursal.setText("Sucursal");
        mnsucursal.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemsucursal.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemsucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/office.png"))); // NOI18N
        mnitemsucursal.setText("Registrar nueva sucursal.");
        mnsucursal.add(mnitemsucursal);

        jMenuBar1.add(mnsucursal);

        mnconductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/driver.png"))); // NOI18N
        mnconductor.setText("Conductores");
        mnconductor.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mniemconductor.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mniemconductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/driver.png"))); // NOI18N
        mniemconductor.setText("Registrar un nuevo conductor.");
        mnconductor.add(mniemconductor);

        jMenuBar1.add(mnconductor);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pay.png"))); // NOI18N
        jMenu2.setText("Pago");
        jMenu2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        jRadioButtonMenuItem2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Registro de pago.");
        jRadioButtonMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pay.png"))); // NOI18N
        jMenu2.add(jRadioButtonMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/operator.png"))); // NOI18N
        jMenu1.setText("consultaequipo");
        jMenu1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Consultausuario");
        jCheckBoxMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userLabel.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("Consultacliente");
        jCheckBoxMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-avatar.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem3);

        jCheckBoxMenuItem5.setSelected(true);
        jCheckBoxMenuItem5.setText("Consultafactura");
        jCheckBoxMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/invoice.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem5);

        jCheckBoxMenuItem7.setSelected(true);
        jCheckBoxMenuItem7.setText("Consultacotizacion");
        jCheckBoxMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bill.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem7);

        jCheckBoxMenuItem8.setSelected(true);
        jCheckBoxMenuItem8.setText("Consultaequipo");
        jCheckBoxMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/computer.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem8);

        consultatransporte.setSelected(true);
        consultatransporte.setText("consultapaquete");
        consultatransporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/box.png"))); // NOI18N
        jMenu1.add(consultatransporte);

        consultaconductores.setSelected(true);
        consultaconductores.setText("Consultatransporte");
        consultaconductores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/truck.png"))); // NOI18N
        jMenu1.add(consultaconductores);

        Consultaempleados.setSelected(true);
        Consultaempleados.setText("Consultapago");
        Consultaempleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pay.png"))); // NOI18N
        jMenu1.add(Consultaempleados);

        jCheckBoxMenuItem11.setSelected(true);
        jCheckBoxMenuItem11.setText("consultapaquetesenelinventario");
        jCheckBoxMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/box.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem11);

        jCheckBoxMenuItem12.setSelected(true);
        jCheckBoxMenuItem12.setText("consultaempleados");
        jCheckBoxMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-avatar.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem12);

        jCheckBoxMenuItem10.setSelected(true);
        jCheckBoxMenuItem10.setText("consultasucursal");
        jCheckBoxMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/office.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem10);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("consultaconductores");
        jCheckBoxMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/driver.png"))); // NOI18N
        jMenu1.add(jCheckBoxMenuItem1);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Consulta receptores.");
        jRadioButtonMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/receiver.png"))); // NOI18N
        jMenu1.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu1);

        mnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        mnsalir.setText("Salir");
        mnsalir.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N

        mnitemsalir.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 14)); // NOI18N
        mnitemsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        mnitemsalir.setText("Salir.");
        mnsalir.add(mnitemsalir);

        jMenuBar1.add(mnsalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btneliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminar1ActionPerformed
        Conexion mysql = new Conexion();
        java.sql.Connection cn = mysql.Conectar();
        ResultSet rs;
        PreparedStatement ps;

        try {
           String clienteID = txtidcliente.getText();
            String query = "select * from clientes where clienteID = ?";
            ps = cn.prepareStatement(query);
            ps.setString(1, clienteID);
            rs = ps.executeQuery();

            if (rs.next()) {
                txtidcliente.setText(rs.getString("clienteID"));
                txtnombre.setText(rs.getString("Nombre"));
                txtapellido.setText(rs.getString("Apellido"));
                txttelefono.setText(rs.getString("Telefono"));
                txtdomicilio.setText(rs.getString("Domicilio"));
                txtnumerodecasa.setText(rs.getString("NumerodeCasa"));
                txtcodigopostal.setText(rs.getString("codigopostal"));
                txtestado.setText(rs.getString("Estado"));
            } else {
                JOptionPane.showMessageDialog(null, "Receptor no encontrado.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al buscar los datos: " + e.getMessage());
        }

    }//GEN-LAST:event_btneliminar1ActionPerformed

    private void txtidclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidclienteActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        Conexion mysql = new Conexion();
        java.sql.Connection cn = mysql.Conectar();

        try {
            String clienteID = txtidcliente.getText();

            String query = "update clientes set Estado = 'Inactivo' where ClienteID = ?";
            try (PreparedStatement ps = cn.prepareStatement(query)) {
                ps.setString(1, clienteID);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Estado del cliente actualizado a 'Inactivo' correctamente.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El ID del cliente debe ser un número válido.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "No se pudo actualizar el estado: " + e.getMessage());
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        this.setVisible(false);
        Opciones opcion = new Opciones();
        opcion.setVisible(true);
    }//GEN-LAST:event_btnvolverActionPerformed

    private void txtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoActionPerformed

    private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarActionPerformed
        ResultSet rs;
        PreparedStatement ps;

        try {
            DefaultTableModel modelo = new DefaultTableModel();
            jTable1.setModel(modelo);

            ps=cn.prepareStatement("SELECT * FROM CLIENTES");
            rs=ps.executeQuery();

            java.sql.ResultSetMetaData rsMd =rs.getMetaData();
            int cColumnas = rsMd.getColumnCount();
            modelo.addColumn("ClienteID");
            modelo.addColumn("Nombre");
            modelo.addColumn("Apellido");
            modelo.addColumn("Telefono");
            modelo.addColumn("Domicilio");
            modelo.addColumn("Numero de Casa");
            modelo.addColumn("Codigo Postal");
            modelo.addColumn("Estado");
            modelo.addColumn("Cédula Receptor");

            while (rs.next()){
                Object[] filas = new Object [cColumnas];
                for (int i=0; i<cColumnas;i++){
                    filas[i]=rs.getObject(i+1);
                }
                modelo.addRow(filas);

            }

        }catch(SQLException e){

            JOptionPane.showMessageDialog(null, "No se pudieron mostrar los datos " + e.getMessage());
        }

    }//GEN-LAST:event_btnmostrarActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        Conexion mysql = new Conexion();
        java.sql.Connection cn = mysql.Conectar();

        String clienteID = txtidcliente.getText();
        String Nombre = txtnombre.getText();
        String Apellido = txtapellido.getText();
        String Telefono = txttelefono.getText();
        String Domicilio = txtdomicilio.getText();
        String Numerodecasa = txtnumerodecasa.getText();
        String Codigopostal = txtcodigopostal.getText();
        String Estado = txtestado.getText();

        String query="Update clientes set  clienteId=?, Nombre=?, Apellido=?, Telefono=?,  Domicilio=?, Numerodecasa=?, Codigopostal=?, Estado=? where clienteId=? ";
        try(PreparedStatement ps=cn.prepareStatement(query))  {

            ps.setString(1, clienteID);
            ps.setString(2, Nombre);
            ps.setString(3, Apellido);
            ps.setString(4, Telefono);
            ps.setString(5, Domicilio);
            ps.setString(6, Numerodecasa);
            ps.setString(7, Codigopostal);
            ps.setString(8, Estado);
            ps.setString(9, clienteID);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "datos actualizados correctamente");

        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "no se pudo actualizar correctamente"+e.getMessage());
        }
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        String clienteID = txtidcliente.getText();
        String nombre = txtnombre.getText();
        String apellido = txtapellido.getText();
        String telefono = txttelefono.getText();
        String domicilio = txtdomicilio.getText();
        String num_casa = txtnumerodecasa.getText();
        String cod_postal = txtcodigopostal.getText();
        String Estado = txtestado.getText();
        

        String clientes = "INSERT INTO clientes(ClienteID, Nombre, Apellido, Telefono,  Domicilio, NumeroDeCasa, CodigoPostal, Estado) values(?, ?, ?, ?, ?, ?, ?, ?);";
        try (PreparedStatement ps = cn.prepareStatement(clientes)){
            ps.setString(1, clienteID);
            ps.setString(2, nombre);
            ps.setString(3, apellido);
            ps.setString(4, telefono);
            ps.setString(5, domicilio);
            ps.setString(6, num_casa);
            ps.setString(7, cod_postal);
            ps.setString(8, Estado);
    

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null,"Datos Guardado correctamente.");
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "No se pudo guardar el Cliente " + e.getMessage());
        }
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void txtdomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdomicilioActionPerformed

    private void txtnumerodecasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumerodecasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumerodecasaActionPerformed

    private void txtapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoActionPerformed

    private void btnregistrarpaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarpaqueteActionPerformed
      this.setVisible(false);
        Tablapaquete paquete = new Tablapaquete ();
        paquete.setVisible(true);
    }//GEN-LAST:event_btnregistrarpaqueteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrocliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrocliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrocliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrocliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrocliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem Consultaempleados;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btneliminar1;
    private javax.swing.JButton btnmostrar;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JButton btnregistrarpaquete;
    private javax.swing.JButton btnvolver;
    private javax.swing.JCheckBoxMenuItem consultaconductores;
    private javax.swing.JCheckBoxMenuItem consultatransporte;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem10;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem11;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem12;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem7;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu mnconductor;
    private javax.swing.JMenu mnequipo;
    private javax.swing.JMenuItem mniemconductor;
    private javax.swing.JMenuItem mnitemcliente;
    private javax.swing.JMenuItem mnitemequipo;
    private javax.swing.JMenuItem mnitempaquete;
    private javax.swing.JMenuItem mnitemreceptor;
    private javax.swing.JMenuItem mnitemsalir;
    private javax.swing.JMenuItem mnitemsucursal;
    private javax.swing.JMenuItem mnitemtransporte;
    private javax.swing.JMenuItem mnitemusuario;
    private javax.swing.JMenu mnpaquete;
    private javax.swing.JMenu mnsalir;
    private javax.swing.JMenu mnsucursal;
    private javax.swing.JMenu mntransporte;
    private javax.swing.JMenu mnusuario;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcodigopostal;
    private javax.swing.JTextField txtdomicilio;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtidcliente;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnumerodecasa;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
